baseurl = "https://beer.blog.castrillon.ch"

[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"

DefaultContentLanguage = "en"
title = "My Beer"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  subtitle = "Notes and thoughts on making my own beer"
  mainSections = ["post","recipes", "page", "howto"] # This controls what is shown in the main page
  logo = "img/beer.png" # Expecting square dimensions
  favicon = "img/beer-favicon.png"
  dateFormat = "02/01/2006"
  custom_css = ["css/custom.css"]
  commit = false # Shows the commit in the published website
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true # Highlight
  delayDisqus = true
  showRelatedPosts = true

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Juan Castrillon"
  email = "jpcr3108@gmail.com"
  github = "juan-castrillon"

[[menu.main]]
    name = "Process"
    url = "page/process/"
    weight = 1

[[menu.main]]
    name = "Recipes"
    url = "recipes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    identifier = "howto"
    name = "HowTo"
    weight = 4

[[menu.main]]
    parent = "howto"
    name = "Ingredient Potential"
    url = "howto/potential"
    weight = 1

[[menu.main]]
    identifier = "others"
    name = "Others"
    weight = 5

[[menu.main]]
    parent = "others"
    name = "Buying Stuff"
    url = "page/buying"
    weight = 1

[[menu.main]]
    parent = "others"
    name = "Calculators"
    url = "page/calculators"
    weight = 2

[[menu.main]]
    parent = "others"
    name = "Learning"
    url = "learn"
    weight = 3

